### ISSUE TITLE
Suggestion: FCNPC_OnPluginError callback

### ISSUE THREAD

**Issue by Yousha** [ziggi/FCNPC#157]
I think its good idea if we have `FCNPC_OnPluginError` callback to track runtime/plugin errors... like other plugins such Streamer

**Comment by WoutProvost** [comment]
What errors are you thinking about?

- the errors that are print to the console log already
- internal errors
- user input validation
- others ...

Regarding the errors that are currently print out to the console (with the **[FCNPC] Error** prefix), most of them are not 'runtime' errors, but errors that should be resolved when the script is being written. So that defeats the purpose of this new callback.

Regarding internal errors, the user doesn't really have much benefit with those. There is already a crashlog feature in place that users don't really know how to interpret, so adding another similar thing to that will only add to the confusion.

Regarding input validation, I can see this as the prime use for a feature like this. However, I'm honestly not that interested, since I haven't seen many people post on the forums with questions regarding why xyz didn't work. You can already detect if something went wrong with the natives based on the return values (e.g. FCNPC_Create returns INVALID_PLAYER_ID if it failed).

**Comment by Yousha** [comment]
**Plugin related** errors, anything

**Comment by ziggi** [comment]
I'm not interested in this feature. But you can make a PR.
