### ISSUE TITLE
OnPlayerEnterDynamicArea Problem

### ISSUE THREAD

**Issue by Recep2112** [ziggi/FCNPC#179]
npc in dynamic area but don't calling OnPlayerEnterDynamicArea

**Comment by WoutProvost** [comment]
Pretty sure this has nothing to do with this plugin. Besides, I recently made a pull request to streamer that should allow NPCs to handle all kinds of item types. However since that update is not yet in new streamer release, you'll have to build the streamer plugin yourself to test it out and explicitely set the streamer to enable area checking for npcs.
[Click](https://github.com/samp-incognito/samp-streamer-plugin/wiki/Natives-(Updates)#streamer_toggleitemupdateplayerid-type-toggle)

**Comment by Recep2112** [comment]
Don't work

**Comment by WoutProvost** [comment]
Given that you didn't even mention the things you tried and just said it doesn't work, I have a suspicion you didn't even try to do what I told you to. I told you **exactly** what to do to get it working. I have seen this pattern way to many times. Saying something doesn't work because you don't want to put in the effort won't get people to help you. If you don't know how to do something, like building the streamer plugin or whatever, just say so. There's nothing embarrasing about that. Don't just say it doesn't work.

Prove that you actually tried the solution I told you and that my suspicion is wrong, or admit it and say what you don't understand. Then you might get some help.

**Comment by WoutProvost** [comment]
Alright, so I've actually compiled the streamer plugin with the latest commits, created an area, created an NPC, enabled area checking for that NPC and guess what ... The NPC calls the callback. It works fine.

Maybe I've been a bit too harsh: so if you want the streamer.dll file that makes area checking work for NPCs, message me on discord.
