### ISSUE TITLE
Support for OMP

### ISSUE THREAD

**Issue by Abyss-z94** [ziggi/FCNPC#269]
Could you do a version that could run on OMP Beta Server just released? That would be awesome

**Comment by ziggi** [comment]
No, I'm not planning to do this. I'm almost out of development for SA-MP. For now I'm writing on TypeScript for one RAGEMP project.

The FCNPC requires internal server structures and functions, for SA-MP it uses memory hacking. If you want to make FCNPC working on OMP you should do all memory hacking work again because OMP has closed source code. If the OMP team doesn't provide an extended SDK (with full server structures access), I'm not sure anyone should do the job at all.

But maybe somewhere there will be a young hot crazy guy ready to get this work done.

**Comment by AmyrAhmady** [comment]
@Abyss-z94 Hey, I tried to contact you on discord but seems like you are a but inactive
But yes you are completely right, only to the point you mentioned people should do memory hacking for open.mp, which is wrong, we have an SDK for that, other plugins started adopting and FCNPC is not hard to do (only takes time, everything is available through SDK), needless to say it will be open source on release after beta testing  os over 

I know you are not into SAMP development anymore, hence I wanted to talk to you on Discord
Just sent you a friend request
iAmir#8100 
Would appreciate if you drop me a message or accept my friend request

**Comment by eakwarp** [comment]
@ziggi @AmyrAhmady guys, did you agree on anything?

**Comment by ReshiramZekrom1** [comment]
> @ziggi @AmyrAhmady guys, did you agree on anything?

Guess not

**Comment by ziggi** [comment]
@eakwarp @ReshiramZekrom1 I gave access to the repository to Amir some time ago, all questions to him
