### ISSUE TITLE
Open Mp

### ISSUE THREAD

**Issue by CrhistopherDiaz** [ziggi/FCNPC#294]
[Error] Skipping legacy plugin 'FCNPC'; It requires memory hacking to run and is therefore broken on open.mp. There should be a replacement component supported by open.mp

**Comment by Cyberneticocst** [comment]
Please friend, could you help me to make the plugin work in open mp is that open mp allows access of users with all versions 0.3.7 and 0.3dl to the server without leaving anyone out please help me

**Comment by ziggi** [comment]
It requires a lot of work, so the answer is no.

**Comment by eakwarp** [comment]
with the latest news regarding the samp, the point is to redo the fcnpc to openmp - it has increased many times)

**Comment by ziggi** [comment]
Some time ago I made a private plugin for SA-MP (with a memory hack) and open.mp. And open.mp looks good, the C++ API covers a lot, but no documentation at all. Anyway porting plugin from SA-MP to open.mp requires too much work and I'm not interested in this at all. And I'm not sure that version for open.mp should be created in this repo because it's almost not possible to keep one codebase for SA-MP and open.mp versions. So I think that someone should create NPC plugin for open.mp from scratch and add compatibility layer with scripts witch written for FCNPC.

**Comment by ziggi** [comment]
Open MP developers are working on an NPC plugin that will be compatible with FCNPC. Feel free to help them: https://opencollective.com/openmultiplayer
Track their progress in this PR: https://github.com/openmultiplayer/open.mp/pull/916
