### ISSUE TITLE
GMXing causes OnPlayerConnect to happen twice?

### ISSUE THREAD

**Issue by karimcambridge** [ziggi/FCNPC#58]
Topic ^

**Comment by ziggi** [comment]
This happens on any OS?

**Comment by karimcambridge** [comment]
Windows, haven't checked Ubuntu yet. Will do in like 10 hours or so.

**Comment by ziggi** [comment]
This happens only with `FCNPC_Destory` in `OnGameModeExit`.

**Comment by ziggi** [comment]
The bug happens if `CFunctions::NewPlayer` are calling before the `pNetGame->iGameState` changes from 2 (GAMESTATE_RESTARTING) to 1 (GAMESTATE_RUNNING). So, for fixing that we need to wait for server restarting and, after that, call the function. Possibly need to use threads order, or just add all names to the list and check for server status in ProcessTick.

**Comment by ziggi** [comment]
34379dcdad418004963db322684f789df2507c44
