### ISSUE TITLE
Accurate weapon reload and shoot times

### ISSUE THREAD

**Issue by WoutProvost** [ziggi/FCNPC#74]
- Get accurate reload times for single weapons.
- Get accurate reload times for double handed weapons (possibly just the former multiplied by 2).
- Get accurate shoot times for single weapons.
- Get accurate shoot times for double handed weapons.
- Check other weapons times as well.

**Comment by ziggi** [comment]
> Get accurate reload times for double handed weapons (possibly just the former multiplied by 2).

Multiply by 2 does not match.

For WEAPON_SAWEDOFF I do this way: https://github.com/ziggi/FCNPC/blob/master/src/CPlayerData.cpp#L1248

But it's pretty dirty, I thing what adding new column to the WeaponInfo array is more acceptable.

**Comment by NegativeIQ** [comment]
Guys keep in mind, in GTA everything depends on FPS. More FPS, faster everything (except the physics on water - driving boats and swimming). Im not sure but i think it all depends on animation speed. Take C bug for example. All it does is drops animation and you can shoot again. So if we want accurate times i guess best way would be extracting animations and checking how long they take to finish. 

By the way,i know there is some ped viewer/editor for GTA, maybe it shows animations duration (i guess its worth a try since im not too keen on importing every single anim in blender/max)

**Comment by WoutProvost** [comment]
Shoot time on colt45 is also not right I think, you hear the npc shoot less times than you see bullet particles appear. However, when you set a higher value than it currently is, it seems to work right.

So probably get accurate shoot times as well.

**Comment by WoutProvost** [comment]
And when were at that, lets just see if the melee swing times are good as well + do all the other weapon types, so that whole that array is good once and for all.

**Comment by ziggi** [comment]
I think what now `times` is pretty good. If anybody is not agreed - change [this array](https://github.com/ziggi/FCNPC/blob/master/src/CWeaponInfo.cpp#L13) and send me a pull request (or just write your data here).
